### ISSUE TITLE
error running camitax

### ISSUE THREAD

**Issue by stefcamp** [abremges/CAMITAX#20]
Dear Andreas,
I have a problem while running camitax. After installation it was working, but after some trials it is no more working, and it is giving an error after few steps. We don't understand if the problem is associated to the docker or to another reason.
I have attached below the ".nextflow.log" in order for you to have an idea of the problem.
I hope you can help.
Thanks in advance.
Sincerely

Stefano

************************************************************************************************************
~~~giu-07 14:53:51.199 [main] DEBUG nextflow.cli.Launcher - $> nextflow run CAMI-challenge/CAMITAX --db /mnt/data_HDD/databases/CAMITAX_db/ --i /mnt/data_HDD/stefano/progetto_proteins_nanopore/selected_MAGs/ --x fa
giu-07 14:53:51.403 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
giu-07 14:53:52.319 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/stefano/.nextflow/assets/CAMI-challenge/CAMITAX/.git/config; branch: master; remote: origin; url: https://github.com/CAMI-challenge/CAMITAX.git
giu-07 14:53:52.331 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/stefano/.nextflow/assets/CAMI-challenge/CAMITAX/.git/config; branch: master; remote: origin; url: https://github.com/CAMI-challenge/CAMITAX.git
giu-07 14:53:52.437 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/stefano/.nextflow/assets/CAMI-challenge/CAMITAX/.git/config; branch: master; remote: origin; url: https://github.com/CAMI-challenge/CAMITAX.git
giu-07 14:53:52.437 [main] INFO  nextflow.cli.CmdRun - Launching `CAMI-challenge/CAMITAX` [big_hodgkin] - revision: 1ed2ac92cc [master]
giu-07 14:53:53.539 [main] INFO  nextflow.scm.AssetManager - NOTE: Your local project version looks outdated - a different revision is available in the remote repository [f7e4933900]
giu-07 14:53:53.557 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/stefano/.nextflow/assets/CAMI-challenge/CAMITAX/nextflow.config
giu-07 14:53:53.558 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/stefano/.nextflow/assets/CAMI-challenge/CAMITAX/nextflow.config
giu-07 14:53:53.578 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
giu-07 14:53:53.718 [main] DEBUG nextflow.Session - Session uuid: 20ac1238-b64b-4bfd-a8dd-9939a1ae20ff
giu-07 14:53:53.718 [main] DEBUG nextflow.Session - Run name: big_hodgkin
giu-07 14:53:53.719 [main] DEBUG nextflow.Session - Executor pool size: 40
giu-07 14:53:53.731 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 19.01.0 build 5050
  Modified: 22-01-2019 11:19 UTC (12:19 CEST)
  System: Linux 4.4.0-150-generic
  Runtime: Groovy 2.5.5 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_201-b09
  Encoding: UTF-8 (UTF-8)
  Process: 65738@loki [127.0.1.1]
  CPUs: 40 - Mem: 251,8 GB (230,9 GB) - Swap: 255,9 GB (255,9 GB)
giu-07 14:53:53.753 [main] DEBUG nextflow.Session - Work-dir: /mnt/data_HDD/stefano/progetto_proteins_nanopore/annotation/work [xfs]
giu-07 14:53:53.969 [main] DEBUG nextflow.Session - Session start invoked
giu-07 14:53:53.976 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
giu-07 14:53:53.977 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
giu-07 14:53:54.529 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
giu-07 14:53:54.570 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /mnt/data_HDD/stefano/progetto_proteins_nanopore/selected_MAGs/; pattern: *.fa; options: [:]
giu-07 14:53:54.886 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:mash` matches process mash
giu-07 14:53:54.891 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:54.891 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:54.899 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:54.902 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
giu-07 14:53:54.907 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=40; memory=251,8 GB; capacity=40; pollInterval=100ms; dumpInterval=5m
giu-07 14:53:54.912 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
giu-07 14:53:54.914 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
giu-07 14:53:54.916 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
giu-07 14:53:54.963 [main] DEBUG nextflow.Session - >>> barrier register (process: mash)
giu-07 14:53:54.967 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > mash -- maxForks: 40
giu-07 14:53:54.999 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:checkm` matches process checkm
giu-07 14:53:55.000 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.000 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.000 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.005 [main] DEBUG nextflow.Session - >>> barrier register (process: checkm)
giu-07 14:53:55.008 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > checkm -- maxForks: 40
giu-07 14:53:55.043 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:dada2` matches process dada2
giu-07 14:53:55.045 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.045 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.045 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.046 [main] DEBUG nextflow.Session - >>> barrier register (process: dada2)
giu-07 14:53:55.046 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > dada2 -- maxForks: 40
giu-07 14:53:55.059 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:prodigal` matches process prodigal
giu-07 14:53:55.060 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.060 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.060 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.061 [main] DEBUG nextflow.Session - >>> barrier register (process: prodigal)
giu-07 14:53:55.061 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > prodigal -- maxForks: 40
giu-07 14:53:55.123 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:centrifuge` matches process centrifuge
giu-07 14:53:55.141 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.141 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.141 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.149 [main] DEBUG nextflow.Session - >>> barrier register (process: centrifuge)
giu-07 14:53:55.149 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > centrifuge -- maxForks: 40
giu-07 14:53:55.192 [main] DEBUG nextflow.util.CacheHelper - Config settings `withName:kaiju` matches process kaiju
giu-07 14:53:55.204 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.204 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.205 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.211 [main] DEBUG nextflow.Session - >>> barrier register (process: kaiju)
giu-07 14:53:55.233 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > kaiju -- maxForks: 40
giu-07 14:53:55.492 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.492 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.492 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.511 [main] DEBUG nextflow.Session - >>> barrier register (process: taxonomy)
giu-07 14:53:55.511 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > taxonomy -- maxForks: 40
giu-07 14:53:55.602 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
giu-07 14:53:55.603 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
giu-07 14:53:55.603 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
giu-07 14:53:55.806 [main] DEBUG nextflow.Session - >>> barrier register (process: summary)
giu-07 14:53:55.807 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > summary -- maxForks: 40
giu-07 14:53:55.813 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
giu-07 14:53:55.815 [main] DEBUG nextflow.Session - Session await
giu-07 14:53:56.190 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.196 [Task submitter] INFO  nextflow.Session - [c9/a016cd] Submitted process > checkm (bin_33_unycicler)
giu-07 14:53:56.221 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.222 [Task submitter] INFO  nextflow.Session - [02/28f124] Submitted process > mash (bin_4_metaspades)
giu-07 14:53:56.239 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.240 [Task submitter] INFO  nextflow.Session - [d8/2319e6] Submitted process > prodigal (bin_33_unycicler)
giu-07 14:53:56.256 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.257 [Task submitter] INFO  nextflow.Session - [c8/2c8e1d] Submitted process > mash (bin_16_metaspades)
giu-07 14:53:56.275 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.289 [Task submitter] INFO  nextflow.Session - [f6/e2d9e3] Submitted process > mash (bin_4_operams)
giu-07 14:53:56.296 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.297 [Task submitter] INFO  nextflow.Session - [68/5509a3] Submitted process > checkm (bin_35_metaspades)
giu-07 14:53:56.305 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.325 [Task submitter] INFO  nextflow.Session - [77/bf1955] Submitted process > mash (bin_5_unycicler)
giu-07 14:53:56.339 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.340 [Task submitter] INFO  nextflow.Session - [83/a3a8c3] Submitted process > prodigal (bin_35_metaspades)
giu-07 14:53:56.349 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.350 [Task submitter] INFO  nextflow.Session - [f7/469646] Submitted process > checkm (bin_14_unycicler)
giu-07 14:53:56.356 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.380 [Task submitter] INFO  nextflow.Session - [38/598252] Submitted process > mash (bin_9_operams)
giu-07 14:53:56.400 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.404 [Task submitter] INFO  nextflow.Session - [87/1390f3] Submitted process > prodigal (bin_2_operams)
giu-07 14:53:56.425 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.433 [Task submitter] INFO  nextflow.Session - [f4/10df77] Submitted process > prodigal (bin_5_unycicler)
giu-07 14:53:56.446 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.446 [Task submitter] INFO  nextflow.Session - [ff/5336cf] Submitted process > prodigal (bin_10_metaspades)
giu-07 14:53:56.456 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.465 [Task submitter] INFO  nextflow.Session - [c9/218269] Submitted process > mash (bin_33_unycicler)
giu-07 14:53:56.474 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.481 [Task submitter] INFO  nextflow.Session - [bb/92fcc3] Submitted process > mash (bin_36_operams)
giu-07 14:53:56.503 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.504 [Task submitter] INFO  nextflow.Session - [c0/d90de9] Submitted process > prodigal (bin_8_metaspades)
giu-07 14:53:56.510 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.511 [Task submitter] INFO  nextflow.Session - [42/a6d15e] Submitted process > mash (bin_28_operams)
giu-07 14:53:56.528 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.528 [Task submitter] INFO  nextflow.Session - [e5/54ee50] Submitted process > prodigal (bin_37_operams)
giu-07 14:53:56.533 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:53:56.534 [Task submitter] INFO  nextflow.Session - [fb/fc2a3c] Submitted process > prodigal (bin_40_metaspades)
giu-07 14:54:05.662 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 101; name: checkm (bin_33_unycicler); status: COMPLETED; exit: 1; error: -; workDir: /mnt/data_HDD/stefano/progetto_proteins_nanopore/annotation/work/c9/a016cd07a3749f119b24599000c5c9]
giu-07 14:54:05.668 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
giu-07 14:54:05.677 [Task submitter] INFO  nextflow.Session - [39/173609] Submitted process > checkm (bin_5_operams)
giu-07 14:54:05.757 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'checkm (bin_33_unycicler)'

Caused by:
  Process `checkm (bin_33_unycicler)` terminated with an error exit status (1)

Command executed:

  # Set CheckM root data location
  echo CAMITAX_db/checkm/ | checkm data setRoot CAMITAX_db/checkm/
  
  # Extract 16S rRNA gene sequences with Nhmmer
  checkm ssu_finder -t 8 -x fa bin_33_unycicler.fa . ssu_finder 2>&1
  ln -s ssu_finder/ssu.fna bin_33_unycicler.ssu.fna
  
  # Phylogenetic placement onto reduced reference tree
  checkm lineage_wf -t 8 --reduced_tree -x fa . checkm
  checkm qa -o 2 --tab_table checkm/lineage.ms checkm > bin_33_unycicler.checkm.tsv

Command exit status:
  1

Command output:
  located at /usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG
  Please try again with updated privileges. Error was:
  
  [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG'
  
  *******************************************************************************
  [CheckM - ssu_finder] Identifying SSU (16S/18S) rRNAs in sequences.
  *******************************************************************************
  
    Determining bin assignment of sequences.
    Identifying SSU rRNAs on sequences.
      Identifying bacterial 16S.
  
  Error: File existence/permissions problem in trying to open query file hmms_ssu/SSU_bacteria.hmm.
  HMM file hmms_ssu/SSU_bacteria.hmm not found (nor an .h3m binary of it)
  
  cat: write error: Broken pipe
      Identifying archaeal 16S.
  
  Error: File existence/permissions problem in trying to open query file hmms_ssu/SSU_archaea.hmm.
  HMM file hmms_ssu/SSU_archaea.hmm not found (nor an .h3m binary of it)
  
  cat: write error: Broken pipe
      Identifying eukaryotic 18S.
  
  Error: File existence/permissions problem in trying to open query file hmms_ssu/SSU_euk.hmm.
  HMM file hmms_ssu/SSU_euk.hmm not found (nor an .h3m binary of it)
  
  cat: write error: Broken pipe
  It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
  You do not seem to have permission to edit the checkm config file
  located at /usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG
  Please try again with updated privileges. Error was:
  
  [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/checkm/DATA_CONFIG'
  Sorry, CheckM cannot run without a valid data folder.
  
  Unexpected error: <type 'exceptions.IOError'>
  Traceback (most recent call last):
    File "/usr/local/bin/checkm", line 709, in <module>
      checkmParser.parseOptions(args)
    File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1312, in parseOptions
      self.ssuFinder(options)
    File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1130, in ssuFinder
      ssuFinder.run(options.seq_file, binFiles, options.out_folder, options.evalue, options.concatenate)
    File "/usr/local/lib/python2.7/site-packages/checkm/ssuFinder.py", line 216, in run
      seqInfo = self.__readHits(os.path.join(outputDir, 'ssu' + '.' + domain + '.txt'), domain, evalueThreshold)
    File "/usr/local/lib/python2.7/site-packages/checkm/ssuFinder.py", line 60, in __readHits
      for line in open(resultsFile):
  IOError: [Errno 2] No such file or directory: 'ssu_finder/ssu.archaea.txt'

Command error:
  
  *******************************************************************************
   [CheckM - data] Check for database updates. [setRoot]
  *******************************************************************************
  
  Data location not changed

Work dir:
  /mnt/data_HDD/stefano/progetto_proteins_nanopore/annotation/work/c9/a016cd07a3749f119b24599000c5c9

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
giu-07 14:54:05.830 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `checkm (bin_33_unycicler)` terminated with an error exit status (1)
giu-07 14:54:05.906 [Task monitor] DEBUG nextflow.Session - The following nodes are still active:
[process] dada2
  status=ACTIVE
  port 0: (value) bound ; channel: db
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] centrifuge
  status=ACTIVE
  port 0: (value) bound ; channel: db
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] kaiju
  status=ACTIVE
  port 0: (value) bound ; channel: db
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] taxonomy
  status=ACTIVE
  port 0: (value) bound ; channel: db
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

[process] summary
  status=ACTIVE
  port 0: (value) OPEN  ; channel: summaryList
  port 1: (cntrl) -     ; channel: $

giu-07 14:54:05.922 [main] DEBUG nextflow.Session - Session await > all process finished
giu-07 14:54:05.922 [main] DEBUG nextflow.Session - Session await > all barriers passed
giu-07 14:54:05.928 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (19)
giu-07 14:54:05.989 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 124; name: prodigal (bin_40_metaspades); status: COMPLETED; exit: 0; error: -; workDir: /mnt/data_HDD/stefano/progetto_proteins_nanopore/annotation/work/fb/fc2a3ce441ea135a5f7063ba4c53db]
giu-07 14:54:06.316 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
giu-07 14:54:06.346 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=1; failedCount=19; ignoredCount=0; cachedCount=0; succeedDuration=9.4s; failedDuration=1m 15s; cachedDuration=0ms]
giu-07 14:54:06.480 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
giu-07 14:54:06.501 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
~~~
edited by Adrian: Fixed md formatting

**Comment by abremges** [comment]
Sorry for not responding earlier, @stefcamp, I was on parental leave and didn't see your issue earlier. 

CAMITAX cannot find or access the CheckM reference data. Did you run `nextflow run CAMI-challenge/CAMITAX/init.nf --db /path/to/db/folder` prior to executing CAMITAX to download the reference data? Else please let me know whether you run CAMITAX with `-profile docker` to make use of BioContainers or installed all dependencies manually, and we'll take it from there.

**Comment by nixon444** [comment]
Hi I keep having this same issue. I thought it was an installation issue (even though it worked fine previously), so I installed on a new virtual machine. I am still getting the same error though with a new installation.

I ran: 

nextflow run CAMI-challenge/CAMITAX -profile docker --db ../../camitax_data/ --i ./ --x fasta

And got this error:

Error executing process > 'checkm (K_1000.001)'

Caused by:
  Process `checkm (K_1000.001)` terminated with an error exit status (126)

Command executed:

  # Set CheckM root data location
  echo camitax_data/checkm/ | checkm data setRoot camitax_data/checkm/
  
  # Extract 16S rRNA gene sequences with Nhmmer
  checkm ssu_finder -t 8 -x fasta K_1000.001.fasta . ssu_finder 2>&1
  ln -s ssu_finder/ssu.fna K_1000.001.ssu.fna
  
  # Phylogenetic placement onto reduced reference tree
  checkm lineage_wf -t 8 --reduced_tree -x fasta . checkm
  checkm qa -o 2 --tab_table checkm/lineage.ms checkm > K_1000.001.checkm.tsv

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=nxf-IA0bM3ooRxKasszrIFcvWZWq: dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /home/ubuntu/camitax_analyses/sharon/work/2d/f08fdbc10808d640d5e3e4ca7368d4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Please help!

**Comment by nixon444** [comment]
I think I have soved this issue - an problem with the docker configuration and permissions on my server. Camitax is now running, so hopefully no more errors!

**Comment by AlphaSquad** [comment]
I'm glad you solved the problem, unfortunately docker sometimes has problems with permissions.
If anything comes up, feel free to reopen
